### Get all persons
GET http://localhost:3001/api/persons
 
### Get all persons as HEAD request
HEAD http://localhost:3001/api/persons

### Get person that exists
GET http://localhost:3001/api/persons/62aba3d938ad5f367c5a03d1

### Get person that doesn't exist
GET http://localhost:3001/api/persons/0

###
DELETE http://localhost:3001/api/persons/1

###
POST http://localhost:3001/api/persons
Content-Type: application/json

{
    "name" : "John Smith",
    "number" : "123-456789"
}

###
POST http://localhost:3001/api/persons
Content-Type: application/json

{
    "name" : "J",
    "number" : ""
}

###
GET http://localhost:3001/api/persons